FONT                = "C:\\Windows\\Fonts\\Tahoma.ttf"

PHOTO_WALLPAPER     = "\\resources\\wallpaper.jpg"

ICON_USERNAME       = "\\resources\\small_icon_user.png"
ICON_PASSWORD       = "\\resources\\small_icon_key.png"
ICON_USERS          = "\\resources\\small_icon_group.png"
ICON_FOLDER         = "\\resources\\small_icon_folder.png"
ICON_FILE           = "\\resources\\small_icon_file.png"
ICON_LISTEN         = "\\resources\\small_icon_listen.png"
ICON_PORT           = "\\resources\\small_icon_code.png"

ICON_COPY           = "\\resources\\small_icon_copy.png"
ICON_SHARE          = "\\resources\\small_icon_share.png"
ICON_INFO           = "\\resources\\small_icon_info.png"
ICON_NEXT           = "\\resources\\small_icon_next.png"
ICON_PREV           = "\\resources\\small_icon_prev.png"
ICON_LOCKED         = "\\resources\\small_icon_lock.png"
ICON_VISIBLE        = "\\resources\\small_icon_visible.png"
ICON_TUNE           = "\\resources\\small_icon_tune.png"
ICON_CHECK          = "\\resources\\small_icon_check.png"
ICON_ADD_FILE       = "\\resources\\small_icon_addfile.png"
ICON_REFRESH        = "\\resources\\small_icon_refresh.png"

TITLE_ICON_CONFIGURE    = "\\resources\\title_configure.png"
TITLE_ICON_FILES        = "\\resources\\title_files.png"
TITLE_ICON_CONNECTION   = "\\resources\\title_connection.png"
TITLE_ICON_LOADING      = "\\resources\\title_loading.png"
TITLE_ICON_WELCOME      = "\\resources\\title_welcome.png"